package mysql

// MySQL data type mapping
var mysqlDataTypeMap = map[string]string{
	"bigint":           "BIGINT",
	"binary":           "BINARY",
	"bit":              "BIT",
	"blob":             "BLOB",
	"bool":             "BOOLEAN",
	"boolean":          "BOOLEAN",
	"char":             "CHAR",
	"date":             "DATE",
	"datetime":         "DATETIME",
	"decimal":          "DECIMAL",
	"double":           "DOUBLE",
	"double precision": "DOUBLE",
	"enum":             "ENUM",
	"float":            "FLOAT",
	"int":              "INT",
	"integer":          "INT",
	"json":             "JSON",
	"longblob":         "LONGBLOB",
	"longtext":         "LONGTEXT",
	"mediumblob":       "MEDIUMBLOB",
	"mediumint":        "MEDIUMINT",
	"mediumtext":       "MEDIUMTEXT",
	"numeric":          "DECIMAL",
	"real":             "DOUBLE",
	"set":              "SET",
	"smallint":         "SMALLINT",
	"text":             "TEXT",
	"time":             "TIME",
	"timestamp":        "TIMESTAMP",
	"tinyblob":         "TINYBLOB",
	"tinyint":          "TINYINT",
	"tinytext":         "TINYTEXT",
	"varbinary":        "VARBINARY",
	"varchar":          "VARCHAR",
	"year":             "YEAR",
}

// MySQL default length mapping
var mysqlDefaultLengthMap = map[string]int{
	"BIGINT":    20,
	"BINARY":    1,
	"BIT":       1,
	"CHAR":      1,
	"DATE":      0,
	"DATETIME":  0,
	"DECIMAL":   10,
	"DOUBLE":    0,
	"FLOAT":     0,
	"INT":       11,
	"MEDIUMINT": 9,
	"SMALLINT":  6,
	"TIME":      0,
	"TIMESTAMP": 0,
	"TINYINT":   4,
	"VARBINARY": 0,
	"VARCHAR":   255,
	"YEAR":      4,
}

// MySQL default precision mapping
var mysqlDefaultPrecisionMap = map[string]int{
	"DECIMAL": 10,
	"DOUBLE":  0,
	"FLOAT":   0,
}

// MySQL default scale mapping
var mysqlDefaultScaleMap = map[string]int{
	"DECIMAL": 0,
	"DOUBLE":  0,
	"FLOAT":   0,
}

// MySQL reserved words
var mysqlReservedWords = []string{
	"accessible", "add", "all", "alter", "analyze", "and", "as", "asc",
	"asensitive", "before", "between", "bigint", "binary", "blob",
	"both", "by", "call", "cascade", "case", "change", "char",
	"character", "check", "collate", "column", "condition",
	"constraint", "continue", "convert", "create", "cross",
	"current_date", "current_time", "current_timestamp", "current_user",
	"cursor", "database", "databases", "day_hour", "day_microsecond",
	"day_minute", "day_second", "dec", "decimal", "declare",
	"default", "delayed", "delete", "desc", "describe", "deterministic",
	"distinct", "distinctrow", "div", "double", "drop", "dual",
	"each", "else", "elseif", "enclosed", "escaped", "exists", "exit",
	"explain", "false", "fetch", "float", "float4", "float8",
	"for", "force", "foreign", "from", "fulltext", "general",
	"grant", "group", "having", "high_priority", "hour_microsecond",
	"hour_minute", "hour_second", "if", "ignore", "in", "index",
	"infile", "inner", "inout", "insensitive", "insert", "int",
	"int1", "int2", "int3", "int4", "int8", "integer", "interval",
	"into", "is", "iterate", "join", "key", "keys", "kill", "leading",
	"leave", "left", "like", "limit", "linear", "lines", "load",
	"localtime", "localtimestamp", "lock", "long", "longblob",
	"longtext", "loop", "low_priority", "master_ssl_verify_server_cert",
	"match", "maxvalue", "mediumblob", "mediumint", "mediumtext",
	"middleint", "minute_microsecond", "minute_second", "mod",
	"modifies", "natural", "not", "no_write_to_binlog", "null",
	"numeric", "on", "optimize", "option", "optionally", "or",
	"order", "out", "outer", "outfile", "precision", "primary",
	"procedure", "purge", "range", "read", "reads", "read_write",
	"real", "references", "regexp", "release", "rename", "repeat",
	"replace", "require", "resignal", "restrict", "return",
	"revoke", "right", "rlike", "schema", "schemas", "second_microsecond",
	"select", "sensitive", "separator", "set", "show", "signal",
	"smallint", "spatial", "specific", "sql", "sqlexception",
	"sqlstate", "sqlwarning", "sql_big_result", "sql_calc_found_rows",
	"sql_small_result", "ssl", "starting", "straight_join", "table",
	"terminated", "then", "tinyblob", "tinyint", "tinytext", "to",
	"trailing", "trigger", "true", "undo", "union", "unique",
	"unlock", "unsigned", "update", "usage", "use", "using",
	"utc_date", "utc_time", "utc_timestamp", "values", "varbinary",
	"varchar", "varcharacter", "varying", "when", "where", "while",
	"with", "write", "xor", "year_month", "zerofill",
}
