package mysql

// Data type conversion maps from MySQL to other database types
var (
	// MySQLToPostgreSQL Data type conversions from MySQL to PostgreSQL
	MySQLToPostgreSQL = map[string]string{
		"tinyint":    "smallint",
		"smallint":   "smallint",
		"mediumint":  "integer",
		"int":        "integer",
		"bigint":     "bigint",
		"float":      "real",
		"double":     "double precision",
		"decimal":    "decimal",
		"char":       "char",
		"varchar":    "varchar",
		"tinytext":   "text",
		"text":       "text",
		"mediumtext": "text",
		"longtext":   "text",
		"json":       "jsonb",
		"datetime":   "timestamp",
		"timestamp":  "timestamp",
		"date":       "date",
		"time":       "time",
		"blob":       "bytea",
		"tinyblob":   "bytea",
		"mediumblob": "bytea",
		"longblob":   "bytea",
		"enum":       "text",
		"set":        "text[]",
		"bool":       "boolean",
		"boolean":    "boolean",
	}

	// MySQLToSQLServer Data type conversions from MySQL to SQL Server
	MySQLToSQLServer = map[string]string{
		"tinyint":    "tinyint",
		"smallint":   "smallint",
		"mediumint":  "int",
		"int":        "int",
		"bigint":     "bigint",
		"float":      "float",
		"double":     "float",
		"decimal":    "decimal",
		"char":       "char",
		"varchar":    "varchar",
		"tinytext":   "varchar(max)",
		"text":       "varchar(max)",
		"mediumtext": "varchar(max)",
		"longtext":   "varchar(max)",
		"json":       "nvarchar(max)",
		"datetime":   "datetime2",
		"timestamp":  "datetime2",
		"date":       "date",
		"time":       "time",
		"blob":       "varbinary(max)",
		"tinyblob":   "varbinary(max)",
		"mediumblob": "varbinary(max)",
		"longblob":   "varbinary(max)",
		"enum":       "varchar(255)",
		"set":        "varchar(max)",
		"bool":       "bit",
		"boolean":    "bit",
	}

	// MySQLToOracle Data type conversions from MySQL to Oracle
	MySQLToOracle = map[string]string{
		"tinyint":    "NUMBER(3)",
		"smallint":   "NUMBER(5)",
		"mediumint":  "NUMBER(7)",
		"int":        "NUMBER(10)",
		"bigint":     "NUMBER(19)",
		"float":      "FLOAT",
		"double":     "FLOAT",
		"decimal":    "NUMBER",
		"char":       "CHAR",
		"varchar":    "VARCHAR2",
		"tinytext":   "CLOB",
		"text":       "CLOB",
		"mediumtext": "CLOB",
		"longtext":   "CLOB",
		"json":       "CLOB",
		"datetime":   "TIMESTAMP",
		"timestamp":  "TIMESTAMP",
		"date":       "DATE",
		"time":       "TIMESTAMP",
		"blob":       "BLOB",
		"tinyblob":   "BLOB",
		"mediumblob": "BLOB",
		"longblob":   "BLOB",
		"enum":       "VARCHAR2(255)",
		"set":        "VARCHAR2(4000)",
		"bool":       "NUMBER(1)",
		"boolean":    "NUMBER(1)",
	}

	// MySQLToSQLite Data type conversions from MySQL to SQLite
	MySQLToSQLite = map[string]string{
		"tinyint":    "INTEGER",
		"smallint":   "INTEGER",
		"mediumint":  "INTEGER",
		"int":        "INTEGER",
		"bigint":     "INTEGER",
		"float":      "REAL",
		"double":     "REAL",
		"decimal":    "REAL",
		"char":       "TEXT",
		"varchar":    "TEXT",
		"tinytext":   "TEXT",
		"text":       "TEXT",
		"mediumtext": "TEXT",
		"longtext":   "TEXT",
		"json":       "TEXT",
		"datetime":   "TEXT",
		"timestamp":  "TEXT",
		"date":       "TEXT",
		"time":       "TEXT",
		"blob":       "BLOB",
		"tinyblob":   "BLOB",
		"mediumblob": "BLOB",
		"longblob":   "BLOB",
		"enum":       "TEXT",
		"set":        "TEXT",
		"bool":       "INTEGER",
		"boolean":    "INTEGER",
	}
)
