package sqlserver

// Data type conversion maps from SQL Server to other database types
var (
	// SQLServerToMySQL Data type conversions from SQL Server to MySQL
	SQLServerToMySQL = map[string]string{
		"tinyint":          "tinyint",
		"smallint":         "smallint",
		"int":              "int",
		"bigint":           "bigint",
		"decimal":          "decimal",
		"numeric":          "decimal",
		"float":            "double",
		"real":             "float",
		"money":            "decimal(19,4)",
		"smallmoney":       "decimal(10,4)",
		"char":             "char",
		"varchar":          "varchar",
		"text":             "text",
		"nchar":            "char",
		"nvarchar":         "varchar",
		"ntext":            "text",
		"binary":           "binary",
		"varbinary":        "varbinary",
		"image":            "longblob",
		"datetime":         "datetime",
		"datetime2":        "datetime",
		"smalldatetime":    "datetime",
		"date":             "date",
		"time":             "time",
		"datetimeoffset":   "datetime",
		"timestamp":        "binary(8)",
		"bit":              "boolean",
		"uniqueidentifier": "char(36)",
		"xml":              "text",
		"sql_variant":      "text",
	}

	// SQLServerToPostgreSQL Data type conversions from SQL Server to PostgreSQL
	SQLServerToPostgreSQL = map[string]string{
		"tinyint":          "smallint",
		"smallint":         "smallint",
		"int":              "integer",
		"bigint":           "bigint",
		"decimal":          "decimal",
		"numeric":          "numeric",
		"float":            "double precision",
		"real":             "real",
		"money":            "money",
		"smallmoney":       "money",
		"char":             "char",
		"varchar":          "varchar",
		"text":             "text",
		"nchar":            "char",
		"nvarchar":         "varchar",
		"ntext":            "text",
		"binary":           "bytea",
		"varbinary":        "bytea",
		"image":            "bytea",
		"datetime":         "timestamp",
		"datetime2":        "timestamp",
		"smalldatetime":    "timestamp",
		"date":             "date",
		"time":             "time",
		"datetimeoffset":   "timestamp with time zone",
		"timestamp":        "bytea",
		"bit":              "boolean",
		"uniqueidentifier": "uuid",
		"xml":              "xml",
		"sql_variant":      "text",
	}

	// SQLServerToOracle Data type conversions from SQL Server to Oracle
	SQLServerToOracle = map[string]string{
		"tinyint":          "NUMBER(3)",
		"smallint":         "NUMBER(5)",
		"int":              "NUMBER(10)",
		"bigint":           "NUMBER(19)",
		"decimal":          "NUMBER",
		"numeric":          "NUMBER",
		"float":            "FLOAT",
		"real":             "FLOAT",
		"money":            "NUMBER(19,4)",
		"smallmoney":       "NUMBER(10,4)",
		"char":             "CHAR",
		"varchar":          "VARCHAR2",
		"text":             "CLOB",
		"nchar":            "NCHAR",
		"nvarchar":         "NVARCHAR2",
		"ntext":            "NCLOB",
		"binary":           "RAW",
		"varbinary":        "BLOB",
		"image":            "BLOB",
		"datetime":         "TIMESTAMP",
		"datetime2":        "TIMESTAMP",
		"smalldatetime":    "TIMESTAMP",
		"date":             "DATE",
		"time":             "TIMESTAMP",
		"datetimeoffset":   "TIMESTAMP WITH TIME ZONE",
		"timestamp":        "RAW(8)",
		"bit":              "NUMBER(1)",
		"uniqueidentifier": "RAW(16)",
		"xml":              "XMLTYPE",
		"sql_variant":      "CLOB",
	}

	// SQLServerToSQLite Data type conversions from SQL Server to SQLite
	SQLServerToSQLite = map[string]string{
		"tinyint":          "INTEGER",
		"smallint":         "INTEGER",
		"int":              "INTEGER",
		"bigint":           "INTEGER",
		"decimal":          "REAL",
		"numeric":          "REAL",
		"float":            "REAL",
		"real":             "REAL",
		"money":            "REAL",
		"smallmoney":       "REAL",
		"char":             "TEXT",
		"varchar":          "TEXT",
		"text":             "TEXT",
		"nchar":            "TEXT",
		"nvarchar":         "TEXT",
		"ntext":            "TEXT",
		"binary":           "BLOB",
		"varbinary":        "BLOB",
		"image":            "BLOB",
		"datetime":         "TEXT",
		"datetime2":        "TEXT",
		"smalldatetime":    "TEXT",
		"date":             "TEXT",
		"time":             "TEXT",
		"datetimeoffset":   "TEXT",
		"timestamp":        "BLOB",
		"bit":              "INTEGER",
		"uniqueidentifier": "TEXT",
		"xml":              "TEXT",
		"sql_variant":      "TEXT",
	}
)
