package postgres

// Data type conversion maps from PostgreSQL to other database types
var (
	// PostgreSQLToMySQL Data type conversions from PostgreSQL to MySQL
	PostgreSQLToMySQL = map[string]string{
		"smallint":         "smallint",
		"integer":          "int",
		"bigint":           "bigint",
		"real":             "float",
		"double precision": "double",
		"decimal":          "decimal",
		"numeric":          "decimal",
		"char":             "char",
		"varchar":          "varchar",
		"text":             "text",
		"jsonb":            "json",
		"json":             "json",
		"timestamp":        "datetime",
		"date":             "date",
		"time":             "time",
		"bytea":            "blob",
		"boolean":          "boolean",
		"uuid":             "varchar(36)",
		"inet":             "varchar(45)",
		"cidr":             "varchar(45)",
		"macaddr":          "varchar(17)",
		"point":            "point",
		"line":             "linestring",
		"lseg":             "linestring",
		"box":              "polygon",
		"path":             "linestring",
		"polygon":          "polygon",
		"circle":           "polygon",
		"interval":         "varchar(255)",
	}

	// PostgreSQLToSQLServer Data type conversions from PostgreSQL to SQL Server
	PostgreSQLToSQLServer = map[string]string{
		"smallint":         "smallint",
		"integer":          "int",
		"bigint":           "bigint",
		"real":             "real",
		"double precision": "float",
		"decimal":          "decimal",
		"numeric":          "decimal",
		"char":             "char",
		"varchar":          "varchar",
		"text":             "varchar(max)",
		"jsonb":            "nvarchar(max)",
		"json":             "nvarchar(max)",
		"timestamp":        "datetime2",
		"date":             "date",
		"time":             "time",
		"bytea":            "varbinary(max)",
		"boolean":          "bit",
		"uuid":             "uniqueidentifier",
		"inet":             "varchar(45)",
		"cidr":             "varchar(45)",
		"macaddr":          "varchar(17)",
		"point":            "geometry",
		"line":             "geometry",
		"lseg":             "geometry",
		"box":              "geometry",
		"path":             "geometry",
		"polygon":          "geometry",
		"circle":           "geometry",
		"interval":         "varchar(255)",
	}

	// PostgreSQLToOracle Data type conversions from PostgreSQL to Oracle
	PostgreSQLToOracle = map[string]string{
		"smallint":         "NUMBER(5)",
		"integer":          "NUMBER(10)",
		"bigint":           "NUMBER(19)",
		"real":             "BINARY_FLOAT",
		"double precision": "BINARY_DOUBLE",
		"decimal":          "NUMBER",
		"numeric":          "NUMBER",
		"char":             "CHAR",
		"varchar":          "VARCHAR2",
		"text":             "CLOB",
		"jsonb":            "CLOB",
		"json":             "CLOB",
		"timestamp":        "TIMESTAMP",
		"date":             "DATE",
		"time":             "TIMESTAMP",
		"bytea":            "BLOB",
		"boolean":          "NUMBER(1)",
		"uuid":             "VARCHAR2(36)",
		"inet":             "VARCHAR2(45)",
		"cidr":             "VARCHAR2(45)",
		"macaddr":          "VARCHAR2(17)",
		"point":            "SDO_GEOMETRY",
		"line":             "SDO_GEOMETRY",
		"lseg":             "SDO_GEOMETRY",
		"box":              "SDO_GEOMETRY",
		"path":             "SDO_GEOMETRY",
		"polygon":          "SDO_GEOMETRY",
		"circle":           "SDO_GEOMETRY",
		"interval":         "INTERVAL DAY TO SECOND",
	}

	// PostgreSQLToSQLite Data type conversions from PostgreSQL to SQLite
	PostgreSQLToSQLite = map[string]string{
		"smallint":         "INTEGER",
		"integer":          "INTEGER",
		"bigint":           "INTEGER",
		"real":             "REAL",
		"double precision": "REAL",
		"decimal":          "REAL",
		"numeric":          "REAL",
		"char":             "TEXT",
		"varchar":          "TEXT",
		"text":             "TEXT",
		"jsonb":            "TEXT",
		"json":             "TEXT",
		"timestamp":        "TEXT",
		"date":             "TEXT",
		"time":             "TEXT",
		"bytea":            "BLOB",
		"boolean":          "INTEGER",
		"uuid":             "TEXT",
		"inet":             "TEXT",
		"cidr":             "TEXT",
		"macaddr":          "TEXT",
		"point":            "TEXT",
		"line":             "TEXT",
		"lseg":             "TEXT",
		"box":              "TEXT",
		"path":             "TEXT",
		"polygon":          "TEXT",
		"circle":           "TEXT",
		"interval":         "TEXT",
	}
)
